/**
 * Course catalog — GENERATED by scripts/extract-courses.js from kb/sql seeds.
 * Do not edit by hand; re-run the script instead.
 *
 * Source: Interview-Preparation-Notes-master → kb/sql/*.sql
 * (121 DSA questions · 28 system design topics · 3 sheets)
 */

export interface CourseQuestion {
  id: string;
  title: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
  source: string;
  leetcodeNumber: number | null;
  tags: string[];
}

export interface CourseTopic {
  id: string;
  title: string;
  kind: "design-question" | "concept";
  description: string;
  keyIdeas: string[];
}

export interface DsaModule {
  id: string;
  title: string;
  kind: "patterns" | "dp";
  description: string;
  questions: CourseQuestion[];
  easy: number;
  medium: number;
  hard: number;
  order: number;
}

export interface SystemDesignModule {
  id: string;
  title: string;
  kind: "concepts" | "designs";
  description: string;
  topics: CourseTopic[];
  order: number;
}

export interface DsaSheet {
  id: string;
  title: string;
  source: string;
  description: string;
  topics: string[];
}

export interface CourseCatalog {
  generatedAt: string;
  dsa: { total: number; modules: DsaModule[] };
  systemDesign: { total: number; modules: SystemDesignModule[] };
  sheets: DsaSheet[];
}

export const COURSE_CATALOG: CourseCatalog = {
  "generatedAt": "2026-09-14",
  "dsa": {
    "total": 121,
    "modules": [
      {
        "id": "dsa-sliding-window",
        "title": "Sliding Window",
        "kind": "patterns",
        "description": "8 curated problems on sliding window — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "maximum-sum-subarray-of-size-k",
            "title": "Maximum Sum Subarray of Size K",
            "category": "sliding-window",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "array",
              "sliding-window"
            ]
          },
          {
            "id": "smallest-subarray-with-given-sum",
            "title": "Smallest Subarray with a given sum",
            "category": "sliding-window",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 209,
            "tags": [
              "array",
              "sliding-window"
            ]
          },
          {
            "id": "longest-substring-k-distinct",
            "title": "Longest Substring with K Distinct Characters",
            "category": "sliding-window",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 340,
            "tags": [
              "string",
              "sliding-window",
              "hash-map"
            ]
          },
          {
            "id": "fruits-into-baskets",
            "title": "Fruits into Baskets",
            "category": "sliding-window",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 904,
            "tags": [
              "array",
              "sliding-window"
            ]
          },
          {
            "id": "no-repeat-substring",
            "title": "No-repeat Substring (Longest Substring without Repeating Characters)",
            "category": "sliding-window",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 3,
            "tags": [
              "string",
              "sliding-window",
              "hash-map"
            ]
          },
          {
            "id": "longest-substring-same-letters-replacement",
            "title": "Longest Substring with Same Letters after Replacement",
            "category": "sliding-window",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 424,
            "tags": [
              "string",
              "sliding-window"
            ]
          },
          {
            "id": "longest-subarray-ones-replacement",
            "title": "Longest Subarray with Ones after Replacement",
            "category": "sliding-window",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 1004,
            "tags": [
              "array",
              "sliding-window"
            ]
          },
          {
            "id": "longest-substring-without-repeating",
            "title": "Longest Substring Without Repeating Characters",
            "category": "sliding-window",
            "difficulty": "medium",
            "source": "python-solutions",
            "leetcodeNumber": 3,
            "tags": [
              "string",
              "sliding-window",
              "hash-map"
            ]
          }
        ],
        "easy": 2,
        "medium": 3,
        "hard": 3,
        "order": 0
      },
      {
        "id": "dsa-two-pointers",
        "title": "Two Pointers",
        "kind": "patterns",
        "description": "8 curated problems on two pointers — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "pair-with-target-sum",
            "title": "Pair with Target Sum (Two Sum II)",
            "category": "two-pointers",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 167,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "remove-duplicates",
            "title": "Remove Duplicates (from Sorted Array)",
            "category": "two-pointers",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 26,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "squaring-a-sorted-array",
            "title": "Squaring a Sorted Array",
            "category": "two-pointers",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 977,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "triplet-sum-to-zero",
            "title": "Triplet Sum to Zero (3Sum)",
            "category": "two-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 15,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "triplet-sum-close-to-target",
            "title": "Triplet Sum Close to Target (3Sum Closest)",
            "category": "two-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 16,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "triplets-with-smaller-sum",
            "title": "Triplets with Smaller Sum",
            "category": "two-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 259,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "subarrays-product-less-than-target",
            "title": "Subarrays with Product Less than a Target",
            "category": "two-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 713,
            "tags": [
              "array",
              "two-pointers"
            ]
          },
          {
            "id": "dutch-national-flag",
            "title": "Dutch National Flag Problem (Sort Colors)",
            "category": "two-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 75,
            "tags": [
              "array",
              "two-pointers",
              "sorting"
            ]
          }
        ],
        "easy": 3,
        "medium": 5,
        "hard": 0,
        "order": 1
      },
      {
        "id": "dsa-fast-slow-pointers",
        "title": "Fast & Slow Pointers",
        "kind": "patterns",
        "description": "3 curated problems on fast & slow pointers — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "linked-list-cycle",
            "title": "LinkedList Cycle",
            "category": "fast-slow-pointers",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 141,
            "tags": [
              "linked-list",
              "two-pointers"
            ]
          },
          {
            "id": "start-of-linked-list-cycle",
            "title": "Start of LinkedList Cycle",
            "category": "fast-slow-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 142,
            "tags": [
              "linked-list",
              "two-pointers"
            ]
          },
          {
            "id": "happy-number",
            "title": "Happy Number",
            "category": "fast-slow-pointers",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 202,
            "tags": [
              "math",
              "hash-map"
            ]
          }
        ],
        "easy": 1,
        "medium": 2,
        "hard": 0,
        "order": 2
      },
      {
        "id": "dsa-merge-intervals",
        "title": "Merge Intervals",
        "kind": "patterns",
        "description": "2 curated problems on merge intervals — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "merge-intervals",
            "title": "Merge Intervals",
            "category": "merge-intervals",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 56,
            "tags": [
              "array",
              "sorting",
              "intervals"
            ]
          },
          {
            "id": "merge-intervals-python",
            "title": "Merge Intervals",
            "category": "merge-intervals",
            "difficulty": "medium",
            "source": "python-solutions",
            "leetcodeNumber": 56,
            "tags": [
              "array",
              "sorting",
              "intervals"
            ]
          }
        ],
        "easy": 0,
        "medium": 2,
        "hard": 0,
        "order": 3
      },
      {
        "id": "dsa-cyclic-sort",
        "title": "Cyclic Sort",
        "kind": "patterns",
        "description": "5 curated problems on cyclic sort — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "cyclic-sort",
            "title": "Cyclic Sort",
            "category": "cyclic-sort",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "array",
              "sorting"
            ]
          },
          {
            "id": "find-the-missing-number",
            "title": "Find the Missing Number",
            "category": "cyclic-sort",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 268,
            "tags": [
              "array",
              "cyclic-sort"
            ]
          },
          {
            "id": "find-all-missing-numbers",
            "title": "Find all Missing Numbers",
            "category": "cyclic-sort",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 448,
            "tags": [
              "array",
              "cyclic-sort"
            ]
          },
          {
            "id": "find-the-duplicate-number",
            "title": "Find the Duplicate Number",
            "category": "cyclic-sort",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 287,
            "tags": [
              "array",
              "cyclic-sort",
              "two-pointers"
            ]
          },
          {
            "id": "find-all-duplicate-numbers",
            "title": "Find all Duplicate Numbers",
            "category": "cyclic-sort",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 442,
            "tags": [
              "array",
              "cyclic-sort"
            ]
          }
        ],
        "easy": 5,
        "medium": 0,
        "hard": 0,
        "order": 4
      },
      {
        "id": "dsa-in-place-reversal",
        "title": "In-place Reversal of a LinkedList",
        "kind": "patterns",
        "description": "3 curated problems on in-place reversal of a linkedlist — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "reverse-a-linked-list",
            "title": "Reverse a LinkedList",
            "category": "in-place-reversal",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 206,
            "tags": [
              "linked-list"
            ]
          },
          {
            "id": "reverse-a-sub-list",
            "title": "Reverse a Sub-list (Reverse Linked List II)",
            "category": "in-place-reversal",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 92,
            "tags": [
              "linked-list"
            ]
          },
          {
            "id": "reverse-every-k-element-sub-list",
            "title": "Reverse every K-element Sub-list",
            "category": "in-place-reversal",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 25,
            "tags": [
              "linked-list"
            ]
          }
        ],
        "easy": 1,
        "medium": 2,
        "hard": 0,
        "order": 5
      },
      {
        "id": "dsa-tree-bfs",
        "title": "Tree Breadth-First Search",
        "kind": "patterns",
        "description": "5 curated problems on tree breadth-first search — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "binary-tree-level-order-traversal",
            "title": "Binary Tree Level Order Traversal",
            "category": "tree-bfs",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 102,
            "tags": [
              "tree",
              "bfs"
            ]
          },
          {
            "id": "reverse-level-order-traversal",
            "title": "Reverse Level Order Traversal",
            "category": "tree-bfs",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 107,
            "tags": [
              "tree",
              "bfs"
            ]
          },
          {
            "id": "level-averages-in-a-binary-tree",
            "title": "Level Averages in a Binary Tree",
            "category": "tree-bfs",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 637,
            "tags": [
              "tree",
              "bfs"
            ]
          },
          {
            "id": "minimum-depth-of-a-binary-tree",
            "title": "Minimum Depth of a Binary Tree",
            "category": "tree-bfs",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 111,
            "tags": [
              "tree",
              "bfs"
            ]
          },
          {
            "id": "level-order-successor",
            "title": "Level Order Successor",
            "category": "tree-bfs",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "tree",
              "bfs"
            ]
          }
        ],
        "easy": 5,
        "medium": 0,
        "hard": 0,
        "order": 6
      },
      {
        "id": "dsa-tree-dfs",
        "title": "Tree Depth-First Search",
        "kind": "patterns",
        "description": "5 curated problems on tree depth-first search — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "binary-tree-path-sum",
            "title": "Binary Tree Path Sum (Path Sum)",
            "category": "tree-dfs",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 112,
            "tags": [
              "tree",
              "dfs"
            ]
          },
          {
            "id": "all-paths-for-a-sum",
            "title": "All Paths for a Sum (Path Sum II)",
            "category": "tree-dfs",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 113,
            "tags": [
              "tree",
              "dfs",
              "backtracking"
            ]
          },
          {
            "id": "sum-of-path-numbers",
            "title": "Sum of Path Numbers",
            "category": "tree-dfs",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 129,
            "tags": [
              "tree",
              "dfs"
            ]
          },
          {
            "id": "path-with-given-sequence",
            "title": "Path With Given Sequence",
            "category": "tree-dfs",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "tree",
              "dfs"
            ]
          },
          {
            "id": "count-paths-for-a-sum",
            "title": "Count Paths for a Sum (Path Sum III)",
            "category": "tree-dfs",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 437,
            "tags": [
              "tree",
              "dfs"
            ]
          }
        ],
        "easy": 1,
        "medium": 4,
        "hard": 0,
        "order": 7
      },
      {
        "id": "dsa-subsets",
        "title": "Subsets",
        "kind": "patterns",
        "description": "6 curated problems on subsets — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "subsets",
            "title": "Subsets",
            "category": "subsets",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 78,
            "tags": [
              "backtracking",
              "bit-manipulation"
            ]
          },
          {
            "id": "subsets-with-duplicates",
            "title": "Subsets With Duplicates",
            "category": "subsets",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 90,
            "tags": [
              "backtracking"
            ]
          },
          {
            "id": "permutations",
            "title": "Permutations",
            "category": "subsets",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 46,
            "tags": [
              "backtracking"
            ]
          },
          {
            "id": "string-permutations-by-changing-case",
            "title": "String Permutations by changing case",
            "category": "subsets",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 784,
            "tags": [
              "backtracking",
              "string"
            ]
          },
          {
            "id": "balanced-parentheses",
            "title": "Balanced Parentheses (Generate Parentheses)",
            "category": "subsets",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 22,
            "tags": [
              "backtracking",
              "string"
            ]
          },
          {
            "id": "unique-generalized-abbreviations",
            "title": "Unique Generalized Abbreviations",
            "category": "subsets",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 320,
            "tags": [
              "backtracking",
              "string"
            ]
          }
        ],
        "easy": 2,
        "medium": 2,
        "hard": 2,
        "order": 8
      },
      {
        "id": "dsa-modified-binary-search",
        "title": "Modified Binary Search",
        "kind": "patterns",
        "description": "7 curated problems on modified binary search — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "order-agnostic-binary-search",
            "title": "Order-agnostic Binary Search (Binary Search)",
            "category": "modified-binary-search",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 704,
            "tags": [
              "binary-search"
            ]
          },
          {
            "id": "ceiling-of-a-number",
            "title": "Ceiling of a Number (Search Insert Position)",
            "category": "modified-binary-search",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 35,
            "tags": [
              "binary-search"
            ]
          },
          {
            "id": "next-letter",
            "title": "Next Letter (Smallest Letter Greater Than Target)",
            "category": "modified-binary-search",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 744,
            "tags": [
              "binary-search",
              "string"
            ]
          },
          {
            "id": "number-range",
            "title": "Number Range (First and Last Position)",
            "category": "modified-binary-search",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 34,
            "tags": [
              "binary-search"
            ]
          },
          {
            "id": "search-in-sorted-infinite-array",
            "title": "Search in a Sorted Infinite Array",
            "category": "modified-binary-search",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 702,
            "tags": [
              "binary-search"
            ]
          },
          {
            "id": "minimum-difference-element",
            "title": "Minimum Difference Element",
            "category": "modified-binary-search",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "binary-search"
            ]
          },
          {
            "id": "bitonic-array-maximum",
            "title": "Bitonic Array Maximum (Peak Index in a Mountain Array)",
            "category": "modified-binary-search",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 852,
            "tags": [
              "binary-search"
            ]
          }
        ],
        "easy": 2,
        "medium": 5,
        "hard": 0,
        "order": 9
      },
      {
        "id": "dsa-bitwise-xor",
        "title": "Bitwise XOR",
        "kind": "patterns",
        "description": "3 curated problems on bitwise xor — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "single-number",
            "title": "Single Number",
            "category": "bitwise-xor",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 136,
            "tags": [
              "bit-manipulation"
            ]
          },
          {
            "id": "two-single-numbers",
            "title": "Two Single Numbers (Single Number III)",
            "category": "bitwise-xor",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 260,
            "tags": [
              "bit-manipulation"
            ]
          },
          {
            "id": "complement-of-base-10-number",
            "title": "Complement of Base 10 Number (Number Complement)",
            "category": "bitwise-xor",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 476,
            "tags": [
              "bit-manipulation"
            ]
          }
        ],
        "easy": 1,
        "medium": 2,
        "hard": 0,
        "order": 10
      },
      {
        "id": "dsa-top-k-elements",
        "title": "Top K Elements",
        "kind": "patterns",
        "description": "9 curated problems on top k elements — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "top-k-numbers",
            "title": "Top K Numbers",
            "category": "top-k-elements",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "heap"
            ]
          },
          {
            "id": "kth-smallest-number",
            "title": "Kth Smallest Number",
            "category": "top-k-elements",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "heap"
            ]
          },
          {
            "id": "k-closest-points-to-origin",
            "title": "K Closest Points to the Origin",
            "category": "top-k-elements",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 973,
            "tags": [
              "heap",
              "geometry"
            ]
          },
          {
            "id": "connect-ropes",
            "title": "Connect Ropes (Minimum Cost to Connect Sticks)",
            "category": "top-k-elements",
            "difficulty": "easy",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 1167,
            "tags": [
              "heap",
              "greedy"
            ]
          },
          {
            "id": "top-k-frequent-numbers",
            "title": "Top K Frequent Numbers (Top K Frequent Elements)",
            "category": "top-k-elements",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 347,
            "tags": [
              "heap",
              "hash-map"
            ]
          },
          {
            "id": "frequency-sort",
            "title": "Frequency Sort (Sort Characters By Frequency)",
            "category": "top-k-elements",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 451,
            "tags": [
              "heap",
              "hash-map",
              "string"
            ]
          },
          {
            "id": "k-closest-numbers",
            "title": "K Closest Numbers (Find K Closest Elements)",
            "category": "top-k-elements",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 658,
            "tags": [
              "heap",
              "binary-search"
            ]
          },
          {
            "id": "maximum-distinct-elements",
            "title": "Maximum Distinct Elements",
            "category": "top-k-elements",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 1481,
            "tags": [
              "heap",
              "greedy"
            ]
          },
          {
            "id": "rearrange-string",
            "title": "Rearrange String",
            "category": "top-k-elements",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 767,
            "tags": [
              "heap",
              "greedy",
              "string"
            ]
          }
        ],
        "easy": 4,
        "medium": 4,
        "hard": 1,
        "order": 11
      },
      {
        "id": "dsa-two-heaps",
        "title": "Two Heaps",
        "kind": "patterns",
        "description": "3 curated problems on two heaps — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "find-median-of-number-stream",
            "title": "Find the Median of a Number Stream",
            "category": "two-heaps",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 295,
            "tags": [
              "heap"
            ]
          },
          {
            "id": "sliding-window-median",
            "title": "Sliding Window Median",
            "category": "two-heaps",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 480,
            "tags": [
              "heap",
              "sliding-window"
            ]
          },
          {
            "id": "maximize-capital",
            "title": "Maximize Capital (IPO)",
            "category": "two-heaps",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 502,
            "tags": [
              "heap",
              "greedy"
            ]
          }
        ],
        "easy": 0,
        "medium": 1,
        "hard": 2,
        "order": 12
      },
      {
        "id": "dsa-k-way-merge",
        "title": "K-way Merge",
        "kind": "patterns",
        "description": "5 curated problems on k-way merge — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "merge-k-sorted-lists",
            "title": "Merge K Sorted Lists",
            "category": "k-way-merge",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 23,
            "tags": [
              "heap",
              "linked-list"
            ]
          },
          {
            "id": "kth-smallest-in-m-sorted-lists",
            "title": "Kth Smallest Number in M Sorted Lists",
            "category": "k-way-merge",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "heap"
            ]
          },
          {
            "id": "kth-smallest-in-sorted-matrix",
            "title": "Kth Smallest Number in a Sorted Matrix",
            "category": "k-way-merge",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 378,
            "tags": [
              "heap",
              "binary-search"
            ]
          },
          {
            "id": "smallest-number-range",
            "title": "Smallest Number Range (Smallest Range from K Lists)",
            "category": "k-way-merge",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 632,
            "tags": [
              "heap",
              "sliding-window"
            ]
          },
          {
            "id": "kth-smallest-number-hard",
            "title": "Kth Smallest Number (hard variant)",
            "category": "k-way-merge",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "heap"
            ]
          }
        ],
        "easy": 0,
        "medium": 2,
        "hard": 3,
        "order": 13
      },
      {
        "id": "dsa-topological-sort",
        "title": "Topological Sort (Graphs)",
        "kind": "patterns",
        "description": "5 curated problems on topological sort (graphs) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "topological-sort",
            "title": "Topological Sort",
            "category": "topological-sort",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "graph",
              "bfs",
              "dfs"
            ]
          },
          {
            "id": "tasks-scheduling",
            "title": "Tasks Scheduling (Course Schedule)",
            "category": "topological-sort",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 207,
            "tags": [
              "graph",
              "bfs"
            ]
          },
          {
            "id": "tasks-scheduling-order",
            "title": "Tasks Scheduling Order (Course Schedule II)",
            "category": "topological-sort",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 210,
            "tags": [
              "graph",
              "bfs"
            ]
          },
          {
            "id": "all-tasks-scheduling-orders",
            "title": "All Tasks Scheduling Orders",
            "category": "topological-sort",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "graph",
              "backtracking"
            ]
          },
          {
            "id": "alien-dictionary",
            "title": "Alien Dictionary",
            "category": "topological-sort",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 269,
            "tags": [
              "graph",
              "bfs"
            ]
          }
        ],
        "easy": 0,
        "medium": 3,
        "hard": 2,
        "order": 14
      },
      {
        "id": "dsa-0-1-knapsack",
        "title": "0/1 Knapsack (DP)",
        "kind": "dp",
        "description": "7 curated problems on 0/1 knapsack (dp) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "equal-subset-sum-partition",
            "title": "Equal Subset Sum Partition",
            "category": "0-1-knapsack",
            "difficulty": "medium",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": 416,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "minimum-subset-sum-difference",
            "title": "Minimum Subset Sum Difference",
            "category": "0-1-knapsack",
            "difficulty": "hard",
            "source": "grokking-coding-patterns",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "01-knapsack",
            "title": "0/1 Knapsack",
            "category": "0-1-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "subset-sum",
            "title": "Subset Sum",
            "category": "0-1-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "minimum-subset-sum-difference-dp",
            "title": "Minimum Subset Sum Difference",
            "category": "0-1-knapsack",
            "difficulty": "hard",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "count-of-subset-sum",
            "title": "Count of Subset Sum",
            "category": "0-1-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "target-sum",
            "title": "Target Sum",
            "category": "0-1-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 494,
            "tags": [
              "dp",
              "knapsack"
            ]
          }
        ],
        "easy": 0,
        "medium": 5,
        "hard": 2,
        "order": 15
      },
      {
        "id": "dsa-unbounded-knapsack",
        "title": "Unbounded Knapsack (DP)",
        "kind": "dp",
        "description": "5 curated problems on unbounded knapsack (dp) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "unbounded-knapsack",
            "title": "Unbounded Knapsack",
            "category": "unbounded-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "rod-cutting",
            "title": "Rod Cutting",
            "category": "unbounded-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "coin-change",
            "title": "Coin Change (unbounded, count combinations)",
            "category": "unbounded-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 518,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "minimum-coin-change",
            "title": "Minimum Coin Change",
            "category": "unbounded-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 322,
            "tags": [
              "dp",
              "knapsack"
            ]
          },
          {
            "id": "maximum-ribbon-cut",
            "title": "Maximum Ribbon Cut",
            "category": "unbounded-knapsack",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "knapsack"
            ]
          }
        ],
        "easy": 0,
        "medium": 5,
        "hard": 0,
        "order": 16
      },
      {
        "id": "dsa-fibonacci-numbers",
        "title": "Fibonacci Numbers (DP)",
        "kind": "dp",
        "description": "6 curated problems on fibonacci numbers (dp) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "fibonacci-numbers",
            "title": "Fibonacci Numbers",
            "category": "fibonacci-numbers",
            "difficulty": "easy",
            "source": "grokking-dp",
            "leetcodeNumber": 509,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "staircase",
            "title": "Staircase (Climbing Stairs)",
            "category": "fibonacci-numbers",
            "difficulty": "easy",
            "source": "grokking-dp",
            "leetcodeNumber": 70,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "number-factors",
            "title": "Number factors",
            "category": "fibonacci-numbers",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "minimum-jumps-to-reach-the-end",
            "title": "Minimum jumps to reach the end (Jump Game II)",
            "category": "fibonacci-numbers",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 45,
            "tags": [
              "dp",
              "greedy"
            ]
          },
          {
            "id": "minimum-jumps-with-fee",
            "title": "Minimum jumps with fee",
            "category": "fibonacci-numbers",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "house-thief",
            "title": "House thief (House Robber)",
            "category": "fibonacci-numbers",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 198,
            "tags": [
              "dp"
            ]
          }
        ],
        "easy": 2,
        "medium": 4,
        "hard": 0,
        "order": 17
      },
      {
        "id": "dsa-palindromic-subsequence",
        "title": "Palindromic Subsequence (DP)",
        "kind": "dp",
        "description": "5 curated problems on palindromic subsequence (dp) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "longest-palindromic-subsequence",
            "title": "Longest Palindromic Subsequence",
            "category": "palindromic-subsequence",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 516,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "longest-palindromic-substring-dp",
            "title": "Longest Palindromic Substring",
            "category": "palindromic-subsequence",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 5,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "count-of-palindromic-substrings",
            "title": "Count of Palindromic Substrings",
            "category": "palindromic-subsequence",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 647,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "minimum-deletions-to-make-palindrome",
            "title": "Minimum Deletions in a String to make it a Palindrome",
            "category": "palindromic-subsequence",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 1312,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "palindromic-partitioning",
            "title": "Palindromic Partitioning",
            "category": "palindromic-subsequence",
            "difficulty": "hard",
            "source": "grokking-dp",
            "leetcodeNumber": 131,
            "tags": [
              "dp",
              "backtracking"
            ]
          }
        ],
        "easy": 0,
        "medium": 4,
        "hard": 1,
        "order": 18
      },
      {
        "id": "dsa-lcs",
        "title": "Longest Common Subsequence (DP)",
        "kind": "dp",
        "description": "8 curated problems on longest common subsequence (dp) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "longest-common-substring",
            "title": "Longest Common Substring",
            "category": "lcs",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "longest-common-subsequence",
            "title": "Longest Common Subsequence",
            "category": "lcs",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 1143,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "min-deletions-insertions-transform",
            "title": "Minimum Deletions & Insertions to Transform a String into another",
            "category": "lcs",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 583,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "shortest-common-supersequence",
            "title": "Shortest Common Super-sequence",
            "category": "lcs",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 1092,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "longest-repeating-subsequence",
            "title": "Longest Repeating Subsequence",
            "category": "lcs",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "subsequence-pattern-matching",
            "title": "Subsequence Pattern Matching (Is Subsequence)",
            "category": "lcs",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 392,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "strings-interleaving",
            "title": "Strings Interleaving (Interleaving String)",
            "category": "lcs",
            "difficulty": "hard",
            "source": "grokking-dp",
            "leetcodeNumber": 97,
            "tags": [
              "dp",
              "string"
            ]
          },
          {
            "id": "edit-distance",
            "title": "Edit Distance",
            "category": "lcs",
            "difficulty": "hard",
            "source": "grokking-dp",
            "leetcodeNumber": 72,
            "tags": [
              "dp",
              "string"
            ]
          }
        ],
        "easy": 0,
        "medium": 6,
        "hard": 2,
        "order": 19
      },
      {
        "id": "dsa-lis",
        "title": "Longest Increasing Subsequence (DP)",
        "kind": "dp",
        "description": "5 curated problems on longest increasing subsequence (dp) — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "longest-increasing-subsequence",
            "title": "Longest Increasing Subsequence",
            "category": "lis",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": 300,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "maximum-sum-increasing-subsequence",
            "title": "Maximum Sum Increasing Subsequence",
            "category": "lis",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "minimum-deletions-to-make-sequence-sorted",
            "title": "Minimum Deletions to Make a Sequence Sorted",
            "category": "lis",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "longest-bitonic-subsequence",
            "title": "Longest Bitonic Subsequence",
            "category": "lis",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          },
          {
            "id": "longest-alternating-subsequence",
            "title": "Longest Alternating Subsequence",
            "category": "lis",
            "difficulty": "medium",
            "source": "grokking-dp",
            "leetcodeNumber": null,
            "tags": [
              "dp"
            ]
          }
        ],
        "easy": 0,
        "medium": 5,
        "hard": 0,
        "order": 20
      },
      {
        "id": "dsa-hashing",
        "title": "Hashing & Hash Maps",
        "kind": "patterns",
        "description": "3 curated problems on hashing & hash maps — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "two-sum",
            "title": "Two Sum",
            "category": "hashing",
            "difficulty": "easy",
            "source": "python-solutions",
            "leetcodeNumber": 1,
            "tags": [
              "array",
              "hash-map"
            ]
          },
          {
            "id": "group-anagrams",
            "title": "Group Anagrams",
            "category": "hashing",
            "difficulty": "medium",
            "source": "python-solutions",
            "leetcodeNumber": 49,
            "tags": [
              "string",
              "hash-map"
            ]
          },
          {
            "id": "valid-anagram",
            "title": "Valid Anagram",
            "category": "hashing",
            "difficulty": "easy",
            "source": "python-solutions",
            "leetcodeNumber": 242,
            "tags": [
              "string",
              "hash-map"
            ]
          }
        ],
        "easy": 2,
        "medium": 1,
        "hard": 0,
        "order": 21
      },
      {
        "id": "dsa-arrays",
        "title": "Arrays",
        "kind": "patterns",
        "description": "3 curated problems on arrays — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "best-time-to-buy-and-sell-stock",
            "title": "Best Time to Buy and Sell Stock",
            "category": "arrays",
            "difficulty": "easy",
            "source": "python-solutions",
            "leetcodeNumber": 121,
            "tags": [
              "array",
              "greedy"
            ]
          },
          {
            "id": "product-of-array-except-self",
            "title": "Product of Array Except Self",
            "category": "arrays",
            "difficulty": "medium",
            "source": "python-solutions",
            "leetcodeNumber": 238,
            "tags": [
              "array",
              "prefix-sum"
            ]
          },
          {
            "id": "maximum-subarray",
            "title": "Maximum Subarray",
            "category": "arrays",
            "difficulty": "medium",
            "source": "python-solutions",
            "leetcodeNumber": 53,
            "tags": [
              "array",
              "kadanes"
            ]
          }
        ],
        "easy": 1,
        "medium": 2,
        "hard": 0,
        "order": 22
      },
      {
        "id": "dsa-strings",
        "title": "Strings",
        "kind": "patterns",
        "description": "2 curated problems on strings — pattern intro, guided examples, and practice set.",
        "questions": [
          {
            "id": "longest-palindromic-substring",
            "title": "Longest Palindromic Substring",
            "category": "strings",
            "difficulty": "medium",
            "source": "python-solutions",
            "leetcodeNumber": 5,
            "tags": [
              "string",
              "two-pointers"
            ]
          },
          {
            "id": "valid-palindrome",
            "title": "Valid Palindrome",
            "category": "strings",
            "difficulty": "easy",
            "source": "python-solutions",
            "leetcodeNumber": 125,
            "tags": [
              "string",
              "two-pointers"
            ]
          }
        ],
        "easy": 1,
        "medium": 1,
        "hard": 0,
        "order": 23
      }
    ]
  },
  "systemDesign": {
    "total": 28,
    "modules": [
      {
        "id": "sd-concepts",
        "title": "Core Concepts",
        "kind": "concepts",
        "description": "The building blocks every design answer needs: caching, load balancing, partitioning, CAP, consistent hashing and more.",
        "topics": [
          {
            "id": "system-design-interviews-step-by-step",
            "title": "System Design Interviews: A step by step guide",
            "kind": "concept",
            "description": "A repeatable 4-step framework for solving any system design interview question.",
            "keyIdeas": []
          },
          {
            "id": "system-design-basics",
            "title": "System Design Basics",
            "kind": "concept",
            "description": "Core primitives used in every distributed system design.",
            "keyIdeas": []
          },
          {
            "id": "key-characteristics-of-distributed-systems",
            "title": "Key Characteristics of Distributed Systems",
            "kind": "concept",
            "description": "The properties systems are designed for: scalability, reliability, availability, efficiency, manageability.",
            "keyIdeas": []
          },
          {
            "id": "load-balancing",
            "title": "Load Balancing",
            "kind": "concept",
            "description": "Distributing client requests across servers to avoid hotspots and enable scaling.",
            "keyIdeas": []
          },
          {
            "id": "caching",
            "title": "Caching",
            "kind": "concept",
            "description": "Storing hot data closer to the consumer to cut latency and DB load.",
            "keyIdeas": []
          },
          {
            "id": "data-partitioning",
            "title": "Data Partitioning",
            "kind": "concept",
            "description": "Splitting a dataset across machines: horizontal (sharding by key) vs vertical (by feature).",
            "keyIdeas": []
          },
          {
            "id": "indexes",
            "title": "Indexes",
            "kind": "concept",
            "description": "Data structures that speed up lookups at the cost of write overhead.",
            "keyIdeas": []
          },
          {
            "id": "proxies",
            "title": "Proxies",
            "kind": "concept",
            "description": "An intermediary between client and server: forward proxy vs reverse proxy.",
            "keyIdeas": []
          },
          {
            "id": "redundancy-and-replication",
            "title": "Redundancy and Replication",
            "kind": "concept",
            "description": "Having multiple copies of data/components to survive failures.",
            "keyIdeas": []
          },
          {
            "id": "sql-vs-nosql",
            "title": "SQL vs NoSQL",
            "kind": "concept",
            "description": "Choosing the right storage engine for the workload.",
            "keyIdeas": []
          },
          {
            "id": "cap-theorem",
            "title": "CAP Theorem",
            "kind": "concept",
            "description": "Under a partition, a distributed system must choose between consistency and availability.",
            "keyIdeas": []
          },
          {
            "id": "consistent-hashing",
            "title": "Consistent Hashing",
            "kind": "concept",
            "description": "A hash-ring technique that keeps key distribution stable when nodes join/leave.",
            "keyIdeas": []
          },
          {
            "id": "long-polling-vs-websockets-vs-sse",
            "title": "Long Polling vs WebSockets vs Server Sent Events",
            "kind": "concept",
            "description": "Push-notification mechanisms and when to use each.",
            "keyIdeas": []
          }
        ],
        "order": 0
      },
      {
        "id": "sd-designs",
        "title": "Design Questions",
        "kind": "designs",
        "description": "Walkthrough designs for the classics — Instagram, Twitter, URL shortener, Dropbox, Messenger, YouTube and more.",
        "topics": [
          {
            "id": "design-pastebin",
            "title": "Designing Pastebin",
            "kind": "design-question",
            "description": "Design a pastebin / text-sharing service where users can store text snippets and share them via short URLs.",
            "keyIdeas": []
          },
          {
            "id": "design-instagram",
            "title": "Designing Instagram",
            "kind": "design-question",
            "description": "Design Instagram — a photo/video sharing social network with feeds, followers and likes.",
            "keyIdeas": []
          },
          {
            "id": "design-dropbox",
            "title": "Designing Dropbox",
            "kind": "design-question",
            "description": "Design Dropbox — a cloud file storage and synchronization service.",
            "keyIdeas": []
          },
          {
            "id": "design-facebook-messenger",
            "title": "Designing Facebook Messenger",
            "kind": "design-question",
            "description": "Design Facebook Messenger — a real-time chat application.",
            "keyIdeas": []
          },
          {
            "id": "design-twitter",
            "title": "Designing Twitter",
            "kind": "design-question",
            "description": "Design Twitter — a social network with tweets, followers, timelines and search.",
            "keyIdeas": []
          },
          {
            "id": "design-youtube-netflix",
            "title": "Designing YouTube or Netflix",
            "kind": "design-question",
            "description": "Design a video streaming platform like YouTube or Netflix.",
            "keyIdeas": []
          },
          {
            "id": "design-typeahead-suggestion",
            "title": "Designing Typeahead Suggestion",
            "kind": "design-question",
            "description": "Design a typeahead / search-as-you-type suggestion system (Google autocomplete).",
            "keyIdeas": []
          },
          {
            "id": "design-api-rate-limiter",
            "title": "Designing an API Rate Limiter",
            "kind": "design-question",
            "description": "Design an API rate limiter that throttles clients exceeding allowed request rates.",
            "keyIdeas": []
          },
          {
            "id": "design-twitter-search",
            "title": "Designing Twitter Search",
            "kind": "design-question",
            "description": "Design search over tweets — index and query millions of tweets in real time.",
            "keyIdeas": []
          },
          {
            "id": "design-web-crawler",
            "title": "Designing a Web Crawler",
            "kind": "design-question",
            "description": "Design a web crawler that discovers and downloads pages at scale.",
            "keyIdeas": []
          },
          {
            "id": "design-facebook-newsfeed",
            "title": "Designing Facebook's Newsfeed",
            "kind": "design-question",
            "description": "Design the Facebook newsfeed — a personalized stream of posts from friends/pages.",
            "keyIdeas": []
          },
          {
            "id": "design-yelp-nearby-friends",
            "title": "Designing Yelp or Nearby Friends",
            "kind": "design-question",
            "description": "Design a location-based service like Yelp or Nearby Friends.",
            "keyIdeas": []
          },
          {
            "id": "design-uber-backend",
            "title": "Designing Uber backend",
            "kind": "design-question",
            "description": "Design the Uber backend — matching riders with drivers, live location, pricing.",
            "keyIdeas": []
          },
          {
            "id": "design-ticketmaster",
            "title": "Designing Ticketmaster",
            "kind": "design-question",
            "description": "Design Ticketmaster — high-concurrency event ticketing with seat reservations.",
            "keyIdeas": []
          },
          {
            "id": "design-url-shortener",
            "title": "Designing a URL Shortening service like TinyURL",
            "kind": "design-question",
            "description": "Design a URL shortener — map long URLs to short keys and redirect.",
            "keyIdeas": []
          }
        ],
        "order": 1
      }
    ]
  },
  "sheets": [
    {
      "id": "love-babbar-450",
      "title": "Love Babbar 450 DSA Sheet",
      "source": "love-babbar-450",
      "description": "The 450-problem DSA sheet (xlsx in 03.. DSA-SHEETS/). 15 topic groups, ~450 problems, the de-facto placement sheet for Indian engineering students.",
      "topics": [
        "arrays",
        "matrix",
        "strings",
        "searching-sorting",
        "linked-list",
        "bit-manipulation",
        "greedy",
        "backtracking",
        "dynamic-programming",
        "stacks-queues",
        "heap",
        "graph",
        "tree",
        "trie",
        "miscellaneous"
      ]
    },
    {
      "id": "grokking-14-patterns",
      "title": "Grokking the Coding Interview — 14 Patterns",
      "source": "grokking",
      "description": "Pattern-first approach: 16 patterns (sliding window, two pointers, subsets, top K, …) with ~180 lesson files, of which the 77 named problems are seeded in dsa_questions (the rest are intros/reviews/challenges).",
      "topics": [
        "sliding-window",
        "two-pointers",
        "fast-slow-pointers",
        "merge-intervals",
        "cyclic-sort",
        "in-place-reversal",
        "tree-bfs",
        "tree-dfs",
        "subsets",
        "modified-binary-search",
        "bitwise-xor",
        "top-k-elements",
        "two-heaps",
        "k-way-merge",
        "topological-sort"
      ]
    },
    {
      "id": "striver-a2z",
      "title": "Striver A2Z DSA Course",
      "source": "striver-a2z",
      "description": "Step-by-step DSA roadmap (takeuforward.org) — the method the SOS app already recommends to Year 1 students (see content/kb/tasks/start-dsa-striver.md).",
      "topics": [
        "basics",
        "arrays",
        "binary-search",
        "strings",
        "linked-list",
        "recursion",
        "bit-manipulation",
        "stacks-queues",
        "sliding-window",
        "heaps",
        "greedy",
        "graphs",
        "dp",
        "trie",
        "segment-tree"
      ]
    }
  ]
};
